# Change these first
owner: valentinlehmann # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: PRM-App
    url: https://prm-app.valentinlehmann.de
  - name: PRM-App Backend
    url: https://prm-backend.valentinlehmann.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.valentinlehmann.de
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/valentinlehmann/status/raw/master/assets/logo.png
  name: Status - Valentin Lehmann
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Auf dieser Website kann der Status von verschiedenen Services abgerufen werden.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO